openapi: "3.0.2"
info:
  title: Basic Auth
  version: "1.0"
paths:
  /signup:
    post:
      requestBody:
        required: false
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: OK
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /signin:
    post:
      security:
        - BasicAuth: []
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/UnauthorizedError"
  /protected:
    get:
      security:
        - BasicAuth: []
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/UnauthorizedError"
components:
  responses:
    CreatedSuccess:
      description: Content creation successful
      headers:
        Access-Control-Allow-Origin: http://localhost:3002
        Vary: Origin

    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    User:
      properties:
        username:
          type: string
        password:
          type: string
